<a href="https://colab.research.google.com/github/fouziasharkar/Pyrhon-Libraries/blob/main/Numpy_Fundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
import numpy as np

In [4]:
#np.array
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
#2D & 3D array

d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [9]:
d3 = np.array([[[1,2],[3,4]]])
print(d3)

[[[1 2]
  [3 4]]]


In [11]:
#dtype
print(np.array(a,dtype=float))
print(np.array(a,dtype=bool))

[1. 2. 3.]
[ True  True  True]


In [14]:
#np.arange

b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
c = np.arange(16).reshape(2,2,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [29]:
for i in c:
  print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
#np.ones &np.zeroes
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
#np.random
np.random.random((3,4))

array([[0.30571121, 0.38988436, 0.99538569, 0.77539369],
       [0.23135172, 0.23002894, 0.49796773, 0.80523197],
       [0.65538476, 0.44363071, 0.67926752, 0.59950165]])

In [39]:
#np.linspace
#-10->10 porjonto 10 ta number nibo jeta linspace equal distance e create korbe
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [44]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [48]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
# ndim
#ndm -> number of dimension of matrix
a3.ndim

3

In [53]:
# shape
print(a3)
a3.shape

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [56]:
# size
#elements kotogulo
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [59]:
# itemsize
#koto byte a store ase each element in memory (4 byte or 8 byte)
print(a1.itemsize)
print(a2.itemsize)

4
8


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [61]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [63]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
# vector operations
# arithmetic
print(a1)
print()
print(a2)
print()
a1 * a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [77]:
a1 = np.arange(1,11).reshape(2,5)
a1 = np.round(a1*100)
a1

array([[ 100,  200,  300,  400,  500],
       [ 600,  700,  800,  900, 1000]])

In [78]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=1)

array([ 500, 1000])

In [79]:
np.min(a1,axis=0)

array([100, 200, 300, 400, 500])

In [80]:
np.prod(a1)

4013587096064229376

In [82]:
np.sum(a1)

5500

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

In [100]:
#np.round: Rounds to the nearest integer (or specified decimal place).
#np.ceil: Rounds up to the nearest integer.

print(np.round(32.5)) #nearest integer e round kortese
print(np.round(32.22,decimals=1)) #decimal dile jotoghor bolbo totoghor porjontoi round korbe
print(np.round(32.22,decimals=0))

print()

print(np.ceil(32.1)) #ceil alway round the number to the next integer

32.0
32.2
32.0

33.0


### Indexing and Slicing

In [101]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
#print the number 4 of a2
#a2[row,col]
a2[1,0]

4

In [105]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [106]:
#print number 5
a3[1,0,1]

5

In [107]:
a3[1,1,0]

6

In [108]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
a1[2:5]

array([2, 3, 4])

In [110]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [117]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [118]:
a2[1,::3]

array([4, 7])

In [119]:
a2[0]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [120]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [123]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [124]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [125]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [126]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [130]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [131]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

*  horizontal stacking
*  vertical stacking

In [133]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print()
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [134]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [135]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

*   Horizontal Spliting
*   Vertical Spliting



In [136]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [138]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]